### ISSUE TITLE
Errors while evaluate the model in training progress

### ISSUE THREAD

**Issue by magic428** [mit-han-lab/e3d#16]
Hi, Thanks for your work!

I meet a problem when evaluate the model in training progress or evaluate the pretrained model.
It exit with an AssertionError: `assert coords.shape[0] == len(labels)`

- pytorch version:  1.6.0;
- python version: 3.6;

Could you help me with the problem?

```bash
(pytorch1.4.0) tdmc@tdmc:~/work/guozhij/gitwork/dl-ai/3d-task/e3d/spvnas$ torchpack dist-run -v -np 1 python train.py configs/semantic_kitti/spvcnn/cr0p5.yaml
mpirun --allow-run-as-root -np 1 -H localhost:1 -bind-to none -map-by slot -x CUDA_HOME -x HOME -x LANG -x LC_ADDRESS -x LC_IDENTIFICATION -x LC_MEASUREMENT -x LC_MONETARY -x LC_NAME -x LC_NUMERIC -x LC_PAPER -x LC_TELEPHONE -x LC_TIME -x LD_LIBRARY_PATH -x LESSCLOSE -x LESSOPEN -x LOGNAME -x LS_COLORS -x MAIL -x MASTER_HOST -x PATH -x PS1 -x PWD -x QT_QPA_PLATFORMTHEME -x SHELL -x SHLVL -x SSH_CLIENT -x SSH_CONNECTION -x SSH_TTY -x TERM -x USER -x VIRTUAL_ENV -x XDG_DATA_DIRS -x XDG_RUNTIME_DIR -x XDG_SESSION_ID -x _ -x tdip -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_exclude docker0,lo python train.py configs/semantic_kitti/spvcnn/cr0p5.yaml
[2020-10-28 16:43:15.574] /home/tdmc/work/python_env/pytorch1.4.0/bin/python train.py configs/semantic_kitti/spvcnn/cr0p5.yaml
[2020-10-28 16:43:15.575] Experiment started: "runs/run-cd60bee5".
workers_per_gpu: 8
data:
  num_classes: 19
  ignore_label: 255
  training_size: 19132
train:
  seed: 1588147245
  deterministic: False
dataset:
  name: semantic_kitti
  root: /home/tdmc/data/Dataset/kitti_odom/dataset/sequences
  num_points: 80000
  voxel_size: 0.05
num_epochs: 15
batch_size: 4
criterion:
  name: cross_entropy
  ignore_index: 255
optimizer:
  name: sgd
  lr: 0.24
  weight_decay: 0.0001
  momentum: 0.9
  nesterov: True
scheduler:
  name: cosine_warmup
model:
  name: spvcnn
  cr: 0.5
[2020-10-28 16:43:22.733] Epoch 1/15 started.
[loss] = 0.225: 100% 4783/4783 [2:33:00<00:00,  1.92s/it]  
[2020-10-28 19:16:23.439] Training finished in 2 hours 33 minutes.
 34% 350/1018 [01:51<03:33,  3.13it/s]
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    main()
  File "train.py", line 102, in main
    Saver(),
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torchpack/train/trainer.py", line 39, in train_with_defaults
    callbacks=callbacks)
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torchpack/train/trainer.py", line 88, in train
    self.trigger_epoch()
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torchpack/train/trainer.py", line 156, in trigger_epoch
    self.callbacks.trigger_epoch()
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torchpack/callbacks/callback.py", line 90, in trigger_epoch
    self._trigger_epoch()
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torchpack/callbacks/callback.py", line 308, in _trigger_epoch
    callback.trigger_epoch()
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torchpack/callbacks/callback.py", line 90, in trigger_epoch
    self._trigger_epoch()
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torchpack/callbacks/inference.py", line 29, in _trigger_epoch
    self._trigger()
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torchpack/callbacks/inference.py", line 36, in _trigger
    for feed_dict in tqdm.tqdm(self.dataflow, ncols=0):
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/tqdm/std.py", line 1171, in __iter__
    for obj in iterable:
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 971, in _next_data
    return self._process_data(data)
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tdmc/work/guozhij/gitwork/dl-ai/3d-task/e3d/spvnas/core/datasets/semantic_kitti.py", line 236, in __getitem__
    return_invs=True)
  File "/home/tdmc/work/python_env/pytorch1.4.0/lib/python3.6/site-packages/torchsparse-1.1.0-py3.6-linux-x86_64.egg/torchsparse/utils/helpers.py", line 48, in sparse_quantize
    assert coords.shape[0] == len(labels)
AssertionError

-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[49202,1],0]
  Exit code:    1
--------------------------------------------------------------------------

```

Best,
Gorzhij

**Comment by kentangSJTU** [comment]
Hi Gorzhij,

If I'm understanding correctly, you will encounter this bug each time when you do evaluation. Then is it possible for you to locate the specific scene that causes the assertion error? Thanks!

Best,
Haotian

**Comment by magic428** [comment]
Hi Haotian,

Sorry for such a long delay.

I check the error point and I found the error is in /sequences/08/velodyne/001400.bin and its label, so I just remove it from the validate set, and the error gone! 

Maybe there is some errors in my 001400.label file.

Best,
Gorzhij

**Comment by kentangSJTU** [comment]
Hi Gorzhij,

Thanks a lot for the update. I just packed these two files on my machine in this zip. You may have a try.
[001400.zip](https://github.com/mit-han-lab/e3d/files/5537770/001400.zip)


Best,
Haotian

**Comment by magic428** [comment]
Hi Haotian,

Thanks a lot for the correct label file. I checked the two files' size, and they were indeed different:

`-rwxr-xr-x 1 tdmc tdmc 490K 11月 18 17:25 001400.label
-rw-rw-r-- 1 tdmc tdmc 256K 10月 27 11:09 001400.label.bak
`
and then I rerun the evaluation successfully!

Thanks again!

Best,
Gorzhij
